# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 233afdd0fadc81e630ce880efcc4fb543e55ea6e2fc2f779f59959c84651f47cf9e49fc7144f81559a1d578bb269205c24e104462d5dadf706845b65c968f89f

test:
  secret_key_base: 467050298263ff5701fadf4a7f7f2b1b71b578affb71909ee61a4a5b8e071a931872af80e26d716fdfec8e5e7e8de891ea8dc36c2c2233472d3e5cc190834edd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
